import React from 'react'
import './HomeContent.css'
import { Scrollbars } from 'react-custom-scrollbars';
import { CSSTransition } from 'react-transition-group';


const HomeContent = ( props ) => {
  return (
    // <CSSTransition
    //   in={props.show}
    //   timeout={300}
    //   classNames="Home"
    //   mountOnEnter
    //   unmountOnExit>
      <div className="Content">
        {/* <div className="ContentInner"> */}
        <Scrollbars
          // This will activate auto hide
          autoHide
          // Hide delay in ms
          autoHideTimeout={1000}
          // Duration for hide animation in ms.
          autoHideDuration={200}
          universal>
                Тут ваш контент Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas rerum deserunt quisquam corporis sed nulla quo libero exercitationem voluptate. Officia, nisi. Praesentium odit ad aliquam cum neque alias earum aperiam. Natus blanditiis odit repudiandae totam! Explicabo blanditiis illum deleniti nobis consequuntur ducimus, hic, neque repudiandae laudantium sequi sapiente minus sed aliquid dicta soluta molestias corrupti iure quos delectus earum? Aliquid. Adipisci impedit repudiandae iste dolores? Voluptate laudantium molestias modi, excepturi consequuntur illo ipsum iste dolor perspiciatis quam reiciendis. Quasi dolor quae aliquid fuga nisi pariatur aliquam nesciunt facere voluptatem recusandae. Quidem doloremque ullam natus molestias? Odio officiis, enim esse corrupti cumque tenetur odit magnam sint aliquid libero quas nobis non sequi minima assumenda quia sunt facilis dicta? Ab, corporis soluta. Praesentium molestiae voluptas sapiente magnam excepturi. Expedita deleniti aperiam provident itaque corporis dignissimos alias maiores iusto maxime omnis? Quia sapiente consectetur incidunt ipsum quisquam ut in, repellendus nihil quae minus. Amet quam corrupti optio aliquam, reiciendis cum tempore culpa eum! Optio quisquam temporibus eos incidunt sint mollitia neque. Placeat facilis nisi fugit eum magni laborum laboriosam quidem quam autem velit. Error amet praesentium magni, tenetur nulla beatae laborum odio autem dignissimos itaque tempore quis tempora, mollitia non qui libero quos ex unde animi? Cumque, repudiandae adipisci? Sed consectetur totam unde! Repudiandae fugit, facilis perspiciatis rerum nam accusamus numquam eligendi architecto sit ullam nulla officia totam itaque tempore, voluptas asperiores reprehenderit doloremque molestias eos ad odit illo? Recusandae unde natus fuga? Molestias hic fugit harum ea dicta distinctio quia, sit asperiores est nesciunt dolorum neque dolorem sunt nisi odit aspernatur beatae adipisci nemo minima quidem suscipit. Quasi rerum sed eum aliquid? Error adipisci ipsa, soluta eaque harum laborum dolores ipsam, cupiditate vitae veritatis eius molestiae? Maiores, temporibus aperiam saepe alias similique corporis sit ullam tempora odit nihil eligendi dignissimos, sequi porro!
                Тут ваш контент Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas rerum deserunt quisquam corporis sed nulla quo libero exercitationem voluptate. Officia, nisi. Praesentium odit ad aliquam cum neque alias earum aperiam. Natus blanditiis odit repudiandae totam! Explicabo blanditiis illum deleniti nobis consequuntur ducimus, hic, neque repudiandae laudantium sequi sapiente minus sed aliquid dicta soluta molestias corrupti iure quos delectus earum? Aliquid. Adipisci impedit repudiandae iste dolores? Voluptate laudantium molestias modi, excepturi consequuntur illo ipsum iste dolor perspiciatis quam reiciendis. Quasi dolor quae aliquid fuga nisi pariatur aliquam nesciunt facere voluptatem recusandae. Quidem doloremque ullam natus molestias? Odio officiis, enim esse corrupti cumque tenetur odit magnam sint aliquid libero quas nobis non sequi minima assumenda quia sunt facilis dicta? Ab, corporis soluta. Praesentium molestiae voluptas sapiente magnam excepturi. Expedita deleniti aperiam provident itaque corporis dignissimos alias maiores iusto maxime omnis? Quia sapiente consectetur incidunt ipsum quisquam ut in, repellendus nihil quae minus. Amet quam corrupti optio aliquam, reiciendis cum tempore culpa eum! Optio quisquam temporibus eos incidunt sint mollitia neque. Placeat facilis nisi fugit eum magni laborum laboriosam quidem quam autem velit. Error amet praesentium magni, tenetur nulla beatae laborum odio autem dignissimos itaque tempore quis tempora, mollitia non qui libero quos ex unde animi? Cumque, repudiandae adipisci? Sed consectetur totam unde! Repudiandae fugit, facilis perspiciatis rerum nam accusamus numquam eligendi architecto sit ullam nulla officia totam itaque tempore, voluptas asperiores reprehenderit doloremque molestias eos ad odit illo? Recusandae unde natus fuga? Molestias hic fugit harum ea dicta distinctio quia, sit asperiores est nesciunt dolorum neque dolorem sunt nisi odit aspernatur beatae adipisci nemo minima quidem suscipit. Quasi rerum sed eum aliquid? Error adipisci ipsa, soluta eaque harum laborum dolores ipsam, cupiditate vitae veritatis eius molestiae? Maiores, temporibus aperiam saepe alias similique corporis sit ullam tempora odit nihil eligendi dignissimos, sequi porro!
                Тут ваш контент Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas rerum deserunt quisquam corporis sed nulla quo libero exercitationem voluptate. Officia, nisi. Praesentium odit ad aliquam cum neque alias earum aperiam. Natus blanditiis odit repudiandae totam! Explicabo blanditiis illum deleniti nobis consequuntur ducimus, hic, neque repudiandae laudantium sequi sapiente minus sed aliquid dicta soluta molestias corrupti iure quos delectus earum? Aliquid. Adipisci impedit repudiandae iste dolores? Voluptate laudantium molestias modi, excepturi consequuntur illo ipsum iste dolor perspiciatis quam reiciendis. Quasi dolor quae aliquid fuga nisi pariatur aliquam nesciunt facere voluptatem recusandae. Quidem doloremque ullam natus molestias? Odio officiis, enim esse corrupti cumque tenetur odit magnam sint aliquid libero quas nobis non sequi minima assumenda quia sunt facilis dicta? Ab, corporis soluta. Praesentium molestiae voluptas sapiente magnam excepturi. Expedita deleniti aperiam provident itaque corporis dignissimos alias maiores iusto maxime omnis? Quia sapiente consectetur incidunt ipsum quisquam ut in, repellendus nihil quae minus. Amet quam corrupti optio aliquam, reiciendis cum tempore culpa eum! Optio quisquam temporibus eos incidunt sint mollitia neque. Placeat facilis nisi fugit eum magni laborum laboriosam quidem quam autem velit. Error amet praesentium magni, tenetur nulla beatae laborum odio autem dignissimos itaque tempore quis tempora, mollitia non qui libero quos ex unde animi? Cumque, repudiandae adipisci? Sed consectetur totam unde! Repudiandae fugit, facilis perspiciatis rerum nam accusamus numquam eligendi architecto sit ullam nulla officia totam itaque tempore, voluptas asperiores reprehenderit doloremque molestias eos ad odit illo? Recusandae unde natus fuga? Molestias hic fugit harum ea dicta distinctio quia, sit asperiores est nesciunt dolorum neque dolorem sunt nisi odit aspernatur beatae adipisci nemo minima quidem suscipit. Quasi rerum sed eum aliquid? Error adipisci ipsa, soluta eaque harum laborum dolores ipsam, cupiditate vitae veritatis eius molestiae? Maiores, temporibus aperiam saepe alias similique corporis sit ullam tempora odit nihil eligendi dignissimos, sequi porro!
        {/* </div> */}
        </Scrollbars>
      </div>
    // </CSSTransition>
    
  )
}

export default HomeContent
